---
Resources:
  MyIamUser:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: 
        PasswordResetRequired: true

  MyIamUser2:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: '{{resolve:ssm-secure:SecureSecretString:1}}'
        PasswordResetRequired: true