---
Resources:
  MyIamUser:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: '{{resolve:ssm-secure:SecureSecretString:1}}'
        PasswordResetRequired: false
        