---
Parameters:
  IamUserLoginPassword:
    Type: String
    Default: BadPassword123
Resources:
  MyIamUser:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: !Ref IamUserLoginPassword
