---
Resources:
  AmazonMQBroker:
    Type: AWS::AmazonMQ::Broker
    Properties: 
      AutoMinorVersionUpgrade: true
      BrokerName: MyAmazonMQBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: ACTIVEMQ
      EngineVersion: "5.15.0"
      HostInstanceType: mq.t2.micro
      PubliclyAccessible: false
      Users: 
        - Password: '{{resolve:secretsmanager:/amazonmq/user/password:SecretString:password}}'
          Username: admin1
        - Password: '{{resolve:secretsmanager:/amazonmq/user/password:SecretString:password}}'
          Username: admin2

  AmazonMQBroker2:
    Type: AWS::AmazonMQ::Broker
    Properties: 
      AutoMinorVersionUpgrade: true
      BrokerName: MyAmazonMQBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: ACTIVEMQ
      EngineVersion: "5.15.0"
      HostInstanceType: mq.t2.micro
      PubliclyAccessible: false
      Users: 
        - Password: '{{resolve:secretsmanager:/amazonmq/user/password:SecretString:password}}'
          Username: admin1
