---
Parameters:
  AmazonMQBrokerUserPassword1:
    Type: String
    NoEcho: true
    Default: BadPassword123
  AmazonMQBrokerUserPassword2:
    Type: String
    NoEcho: true
    Default: BadPassword123
  AmazonMQBrokerUserPassword3:
    Type: String
    NoEcho: true
Resources:
  AmazonMQBroker:
    Type: AWS::AmazonMQ::Broker
    Properties: 
      AutoMinorVersionUpgrade: true
      BrokerName: MyAmazonMQBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: ACTIVEMQ
      EngineVersion: "5.15.0"
      HostInstanceType: mq.t2.micro
      PubliclyAccessible: false
      Users: 
        - Password: !Ref AmazonMQBrokerUserPassword1
          Username: admin1
        - Password: !Ref AmazonMQBrokerUserPassword1
          Username: admin2

  AmazonMQBroker2:
    Type: AWS::AmazonMQ::Broker
    Properties: 
      AutoMinorVersionUpgrade: true
      BrokerName: MyAmazonMQBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: ACTIVEMQ
      EngineVersion: "5.15.0"
      HostInstanceType: mq.t2.micro
      PubliclyAccessible: false
      Users: 
        - Password: !Ref AmazonMQBrokerUserPassword2
          Username: admin1

  AmazonMQBroker3:
    Type: AWS::AmazonMQ::Broker
    Properties: 
      AutoMinorVersionUpgrade: true
      BrokerName: MyAmazonMQBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: ACTIVEMQ
      EngineVersion: "5.15.0"
      HostInstanceType: mq.t2.micro
      PubliclyAccessible: false
      Users: 
        - Password: !Ref AmazonMQBrokerUserPassword3
          Username: admin1
