---
Resources:
  MicrosoftAD:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      Name: microsoftad.foobar.com
      Password: '{{resolve:secretsmanager:/rds/db_cluster/masteruserpassword:SecretString:password}}'
      VpcSettings:
        SubnetIds:
          - subnet-foobar
          - subnet-foobaz
        VpcId: vpc-foobar
