---
Resources:
  MyOpsWorksStack:
    Type: AWS::OpsWorks::Stack
    Properties: 
      DefaultInstanceProfileArn: arn:aws:iam::1234567890:instance-profile/MyProfile-ASDNSDLKJ
      Name: MyOpsWorksStack
      ServiceRoleArn: arn:aws:iam::1234567890:role/MyRole-AJJHDSKSDF
  MyOpsWorksStack2:
    Type: AWS::OpsWorks::Stack
    Properties: 
      DefaultInstanceProfileArn: arn:aws:iam::1234567890:instance-profile/MyProfile-ASDNSDLKJ
      Name: MyOpsWorksStack
      ServiceRoleArn: arn:aws:iam::1234567890:role/MyRole-AJJHDSKSDF
        