---
Resources:
  MyOpsWorksStack:
    Type: AWS::OpsWorks::Stack
    Properties: 
      DefaultInstanceProfileArn: arn:aws:iam::1234567890:instance-profile/MyProfile-ASDNSDLKJ
      Name: MyOpsWorksStack
      ServiceRoleArn: arn:aws:iam::1234567890:role/MyRole-AJJHDSKSDF
      RdsDbInstances: 
        - DbPassword: '{{resolve:ssm-secure:SecureSecretString:1}}'
          DbUser: admin
          RdsDbInstanceArn: arn:aws:rds:us-east-2:123456789012:db:my-mysql-instance-1
  MyOpsWorksStack2:
    Type: AWS::OpsWorks::Stack
    Properties: 
      DefaultInstanceProfileArn: arn:aws:iam::1234567890:instance-profile/MyProfile-ASDNSDLKJ
      Name: MyOpsWorksStack
      ServiceRoleArn: arn:aws:iam::1234567890:role/MyRole-AJJHDSKSDF
      RdsDbInstances: 
        - DbPassword: 
          DbUser: admin
          RdsDbInstanceArn: arn:aws:rds:us-east-2:123456789012:db:my-mysql-instance-1
        - DbPassword: '{{resolve:ssm-secure:SecureSecretString:1}}'
          DbUser: admin
          RdsDbInstanceArn: arn:aws:rds:us-east-2:123456789012:db:my-mysql-instance-1
        