---
Parameters:
  OpsWorksStackRdsDbInstancePassword:
    Type: String
    NoEcho: true
  OpsWorksStackRdsDbInstancePassword2:
    Type: String
    NoEcho: true
  OpsWorksStackRdsDbInstancePassword3:
    Type: String
    NoEcho: true
Resources:
  MyOpsWorksStack:
    Type: AWS::OpsWorks::Stack
    Properties: 
      DefaultInstanceProfileArn: arn:aws:iam::1234567890:instance-profile/MyProfile-ASDNSDLKJ
      Name: MyOpsWorksStack
      ServiceRoleArn: arn:aws:iam::1234567890:role/MyRole-AJJHDSKSDF
      RdsDbInstances: 
        - DbPassword: !Ref OpsWorksStackRdsDbInstancePassword
          DbUser: admin
          RdsDbInstanceArn: arn:aws:rds:us-east-2:123456789012:db:my-mysql-instance-1
  MyOpsWorksStack2:
    Type: AWS::OpsWorks::Stack
    Properties: 
      DefaultInstanceProfileArn: arn:aws:iam::1234567890:instance-profile/MyProfile-ASDNSDLKJ
      Name: MyOpsWorksStack
      ServiceRoleArn: arn:aws:iam::1234567890:role/MyRole-AJJHDSKSDF
      RdsDbInstances: 
        - DbPassword: !Ref OpsWorksStackRdsDbInstancePassword2
          DbUser: admin
          RdsDbInstanceArn: arn:aws:rds:us-east-2:123456789012:db:my-mysql-instance-1
  MyOpsWorksStack3:
    Type: AWS::OpsWorks::Stack
    Properties: 
      DefaultInstanceProfileArn: arn:aws:iam::1234567890:instance-profile/MyProfile-ASDNSDLKJ
      Name: MyOpsWorksStack
      ServiceRoleArn: arn:aws:iam::1234567890:role/MyRole-AJJHDSKSDF
      RdsDbInstances: 
        - DbPassword: !Ref OpsWorksStackRdsDbInstancePassword3
          DbUser: admin
          RdsDbInstanceArn: arn:aws:rds:us-east-2:123456789012:db:my-mysql-instance-1
        