---
Resources:
  KendraIndex:
    Type: AWS::Kendra::Index
    Properties:
      Edition: ENTERPRISE_EDITION
      Name: KendraIndexWithoutServerSideEncryptionConfiguration
      RoleArn: arn:aws:iam::123456789012:role/KendraIndex-foobar
